"""
Generates the text for DPDP Act erasure-request correspondence.

Important: these are drafting aids, not legal advice, and the escalation
cadence (day 3 / 7 / 14) is a product-chosen follow-up rhythm, not a
statutory deadline. Every generated letter says so explicitly so a user
never mistakes this for a lawyer's opinion.
"""
from datetime import datetime

LEGAL_DISCLAIMER = (
    "This message was drafted with the help of an automated tool and is not "
    "legal advice. Please review it before sending, and consult a legal "
    "professional if the company disputes your request or you intend to "
    "escalate to the Data Protection Board of India."
)


def _categories_line(data_categories):
    if not data_categories:
        return "the personal data you hold about me"
    return ", ".join(data_categories)


def build_initial_request(*, full_name, email, company_name, data_categories, reason):
    today = datetime.now().strftime("%d %B %Y")
    cats = _categories_line(data_categories)
    reason_line = f"\nReason for this request: {reason}\n" if reason else ""
    return f"""Date: {today}

To: The Grievance Officer / Data Protection Officer, {company_name}

Subject: Request for erasure of personal data under the Digital Personal Data Protection Act, 2023

Dear Sir/Madam,

I, {full_name} ({email}), am writing to exercise my right to correction and
erasure under the Digital Personal Data Protection Act, 2023 (the "DPDP
Act"), as a Data Principal whose personal data you hold as a Data Fiduciary.

I request that you:
1. Confirm what personal data you hold about me, specifically {cats}.
2. Erase this personal data, unless you are required to retain it for a
   specified legal purpose — in which case, please identify that purpose
   and the applicable law.
3. Confirm in writing once this erasure has been completed.
{reason_line}
Please respond to this request through your grievance redressal mechanism
within the timeline required by the DPDP Act and applicable Rules. If I do
not receive a response, I intend to follow up and, if necessary, escalate
this complaint to the Data Protection Board of India.

Regards,
{full_name}
{email}

---
{LEGAL_DISCLAIMER}
"""


def build_reminder(*, full_name, email, company_name, original_sent_date):
    today = datetime.now().strftime("%d %B %Y")
    return f"""Date: {today}

To: The Grievance Officer / Data Protection Officer, {company_name}

Subject: Reminder — Request for erasure of personal data (originally sent {original_sent_date})

Dear Sir/Madam,

This is a follow-up to my personal data erasure request sent on
{original_sent_date}, to which I have not yet received a response. I am
{full_name} ({email}).

Please treat this as a reminder to act on my original request and confirm
the status of my personal data erasure. I look forward to your response at
the earliest.

Regards,
{full_name}
{email}

---
{LEGAL_DISCLAIMER}
"""


def build_legal_notice(*, full_name, email, company_name, original_sent_date, reminder_sent_date):
    today = datetime.now().strftime("%d %B %Y")
    return f"""Date: {today}

To: The Grievance Officer / Data Protection Officer, {company_name}

Subject: Notice before escalation — Unresolved personal data erasure request

Dear Sir/Madam,

I am {full_name} ({email}). I submitted a personal data erasure request to
you on {original_sent_date} under the Digital Personal Data Protection Act,
2023, and sent a reminder on {reminder_sent_date}. I have still not received
a substantive response or confirmation of erasure.

This notice is to inform you that, if I do not receive a response within a
reasonable period from the date of this notice, I intend to file a formal
complaint with the Data Protection Board of India regarding your failure to
respond to a Data Principal's request under the DPDP Act.

I would prefer to resolve this without escalation and welcome your prompt
response.

Regards,
{full_name}
{email}

---
{LEGAL_DISCLAIMER}
This notice was generated by an automated tool at the user's direction. It
is not issued by a law firm or advocate.
"""


def build_complaint_prep_notes(*, full_name, email, company_name, original_sent_date,
                                 reminder_sent_date, legal_notice_sent_date):
    return f"""Complaint preparation summary for {company_name}

Data Principal: {full_name} ({email})

Timeline:
- Erasure request sent: {original_sent_date}
- Reminder sent: {reminder_sent_date}
- Notice before escalation sent: {legal_notice_sent_date}
- No substantive response received as of this summary.

Suggested next step: file a complaint with the Data Protection Board of
India (once its complaint mechanism is operational per applicable Rules),
attaching this timeline and copies of all correspondence logged against
this request.

---
{LEGAL_DISCLAIMER} This summary is a drafting aid only — verify the Data
Protection Board's current complaint process before filing.
"""
