# -*- coding: utf-8 -*-
"""Football shorts base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_aHfOmou_tS7vYSfFwg2vh5jkYN_Dri

# Automated Football Shorts Pipeline

**Legal & sustainable version** — uses original commentary + free stock football footage + AI voiceover + auto-captions, no scraping of broadcast footage.

## Pipeline stages
1. Trend detection (API-Football + news RSS)
2. Script + captions + hashtags (LLM)
3. Voiceover (Edge-TTS, free)
4. B-roll (Pexels free stock football footage)
5. Video assembly (FFmpeg, 9:16, burned-in captions)
6. Word-level captions (Whisper)
7. Upload to YouTube Shorts (YouTube Data API)

## Before running
You'll need free API keys for:
- **API-Football** (RapidAPI free tier): https://rapidapi.com/api-sports/api/api-football
- **Pexels** (free): https://www.pexels.com/api/
- **Anthropic or OpenAI** (for script generation) — or skip and write scripts manually
- **YouTube Data API** OAuth credentials — see separate setup guide

Run cells top to bottom. Each stage saves its output so you can re-run later stages independently.

## 0. Setup — Install dependencies
"""

!pip install -q edge-tts openai-whisper feedparser requests python-dotenv anthropic pillow
!apt-get -qq install -y ffmpeg fonts-dejavu-core > /dev/null

import os
import json
import requests
import feedparser
from datetime import datetime

# Create working dirs
os.makedirs('/content/pipeline/assets', exist_ok=True)
os.makedirs('/content/pipeline/output', exist_ok=True)
print('Setup complete')

"""## 0.1 — API Keys

Paste your free API keys below. For Colab, better practice is to use `Secrets` (key icon on left sidebar) instead of hardcoding — but plain variables work fine to start.
"""

# --- Fill these in ---
PEXELS_API_KEY = "SPvmUBs6mDwAa4yJ5vPIlllEQIPopvC31s9zWY5BW0c2RCcldNgnHcPj"          # https://www.pexels.com/api/
RAPIDAPI_KEY   = "a2d7167127msh9d3e995a63e3021p139363jsn8bf729868965"            # for API-Football, https://rapidapi.com/api-sports/api/api-football
ANTHROPIC_API_KEY = "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"    # https://console.anthropic.com (or use OpenAI instead)

# Optional: if using Colab Secrets instead, uncomment:
# from google.colab import userdata
# PEXELS_API_KEY = userdata.get('PEXELS_API_KEY')
# RAPIDAPI_KEY = userdata.get('RAPIDAPI_KEY')
# ANTHROPIC_API_KEY = userdata.get('ANTHROPIC_API_KEY')

# --- Auto-approve toggle ---
# If True, section 6.1 marks each video as 'approved' immediately (skipping
# the manual review step), so section 7 uploads it without you needing to
# edit the Google Sheet. Set to False to restore the manual review gate.
AUTO_APPROVE = True

print('Keys loaded (values hidden)')

"""## 1. Idea / Trend Generation

Pulls:
- Latest football news headlines from free RSS feeds (BBC Sport, ESPN, Sky Sports)
- Recent World Cup 2026 fixtures/results from API-Football

Then ranks them with an LLM for 'short-worthiness'.

### 1.0 Idea Bank — content categories & search queries

This block defines the **types of ideas** the pipeline looks for each run. Instead of one generic search, it rotates through categories so your channel covers a mix of content (not just match recaps). Each category has its own RSS/search queries and a content-angle hint for the LLM.

You can edit, add, or remove categories/queries any time — the rest of the pipeline just consumes whatever this block produces.
"""

# Idea categories: each has search queries (for news/API lookups) and an 'angle'
# describing what kind of Short this category should produce.

IDEA_CATEGORIES = {
    "match_recap": {
        "queries": ["World Cup 2026 result", "World Cup 2026 score"],
        "angle": "Recap a recent result with key stats (scoreline, goal scorers, possession, shots) - no play-by-play of footage."
    },
    "player_spotlight": {
        "queries": ["World Cup 2026 breakout player", "World Cup 2026 top scorer"],
        "angle": "Highlight a standout player's tournament stats/story - goals, assists, age, background."
    },
    "upset_or_drama": {
        "queries": ["World Cup 2026 upset", "World Cup 2026 shock result", "World Cup 2026 controversy"],
        "angle": "Explain why a result was surprising using stats/odds/form - framed as 'why did X happen'."
    },
    "prediction_preview": {
        "queries": ["World Cup 2026 fixtures today", "World Cup 2026 upcoming matches"],
        "angle": "Preview an upcoming match: head-to-head record, form, key players to watch, prediction."
    },
    "tactical_breakdown": {
        "queries": ["World Cup 2026 tactics", "World Cup 2026 formation analysis"],
        "angle": "Explain a tactical trend (formation, pressing style, set-piece routine) in simple terms with a stat hook."
    },
    "records_milestones": {
        "queries": ["World Cup 2026 record", "World Cup 2026 history milestone"],
        "angle": "Frame a stat as a record/milestone - 'first time since...', 'youngest to...', etc."
    },
}

# Pick which categories to run this session (rotate manually, or randomize)
import random
ACTIVE_CATEGORIES = random.sample(list(IDEA_CATEGORIES.keys()), k=3)
print("Active categories this run:", ACTIVE_CATEGORIES)

# --- 1a. Pull headlines from RSS feeds, then filter by idea-bank category queries ---
RSS_FEEDS = [
    "https://feeds.bbci.co.uk/sport/football/rss.xml",
    "https://www.espn.com/espn/rss/soccer/news",
    "https://www.theguardian.com/football/rss",
]

all_headlines = []
for feed_url in RSS_FEEDS:
    feed = feedparser.parse(feed_url)
    for entry in feed.entries[:20]:
        all_headlines.append({
            "title": entry.title,
            "summary": getattr(entry, 'summary', ''),
            "link": entry.link,
            "published": getattr(entry, 'published', '')
        })

print(f"Pulled {len(all_headlines)} total headlines")

# Group headlines under each active category by simple keyword overlap with the
# category's queries (cheap relevance filter before the LLM ranking step)
def keyword_match(headline_text, queries):
    text = headline_text.lower()
    for q in queries:
        terms = [t.lower() for t in q.split() if t.lower() not in ("world", "cup", "2026")]
        if any(term in text for term in terms):
            return True
    return False

headlines_by_category = {}
for cat in ACTIVE_CATEGORIES:
    queries = IDEA_CATEGORIES[cat]["queries"]
    matched = [h for h in all_headlines if keyword_match(h['title'] + ' ' + h['summary'], queries)]
    # Fallback: if nothing matches, use the general pool so the category isn't empty
    headlines_by_category[cat] = matched if matched else all_headlines[:5]
    print(f"{cat}: {len(headlines_by_category[cat])} candidate headlines")

headlines = all_headlines  # keep for backward compatibility with later cells

import http.client
from datetime import datetime, timedelta

FOOTBALL_API_HOST = "free-api-live-football-data.p.rapidapi.com"

# Add World Cup 2026 leagueId(s) here once known, e.g. [894500]
WORLD_CUP_LEAGUE_IDS = []

def get_matches_by_date(date_str):
    """date_str format: YYYYMMDD"""
    conn = http.client.HTTPSConnection(FOOTBALL_API_HOST, timeout=10)
    headers = {
        'x-rapidapi-key': RAPIDAPI_KEY,
        'x-rapidapi-host': FOOTBALL_API_HOST,
        'Content-Type': "application/json"
    }
    conn.request("GET", f"/football-get-matches-by-date?date={date_str}", headers=headers)
    res = conn.getresponse()
    if res.status != 200:
        raise RuntimeError(f"API error: {res.status} {res.read()[:200]}")
    data = json.loads(res.read().decode("utf-8"))
    if data.get("status") != "success":
        raise RuntimeError(f"API returned non-success status: {data}")
    return data.get("response", {}).get("matches", [])

def parse_match(item):
    home = item.get("home", {})
    away = item.get("away", {})
    status = item.get("status", {})
    return {
        "home": home.get("longName") or home.get("name", ""),
        "away": away.get("longName") or away.get("name", ""),
        "score": status.get("scoreStr", ""),
        "date": item.get("time", ""),
        "finished": status.get("finished", False),
        "leagueId": item.get("leagueId"),
    }

try:
    # Pull yesterday and today (YYYYMMDD format for this API)
    today = datetime.utcnow().date()
    dates_to_check = [today - timedelta(days=1), today]

    all_matches = []
    for d in dates_to_check:
        date_str = d.strftime("%Y%m%d")
        matches = get_matches_by_date(date_str)
        all_matches.extend(parse_match(m) for m in matches)

    print(f"Pulled {len(all_matches)} total matches across {len(dates_to_check)} day(s)")

    # Filter for World Cup 2026 matches
    if WORLD_CUP_LEAGUE_IDS:
        fixtures = [m for m in all_matches if m["leagueId"] in WORLD_CUP_LEAGUE_IDS]
    else:
        # Fallback: match on common national team names (noisy but functional
        # without a known leagueId). Extend this list as needed.
        NATIONAL_TEAMS = [
            "Brazil", "Argentina", "France", "England", "Spain", "Germany",
            "Portugal", "Netherlands", "Belgium", "Italy", "Croatia", "Morocco",
            "USA", "United States", "Mexico", "Japan", "South Korea", "Senegal",
            "Canada", "Uruguay", "Colombia", "Switzerland", "Denmark", "Wales",
            "Ghana", "Cameroon", "Poland", "Serbia", "Australia", "Costa Rica",
            "Ecuador", "Tunisia", "Saudi Arabia", "Qatar", "Iran", "Nigeria"
        ]
        fixtures = [
            m for m in all_matches
            if m["home"] in NATIONAL_TEAMS and m["away"] in NATIONAL_TEAMS
        ]

    print(f"Filtered to {len(fixtures)} likely World Cup / international matches")
    for f in fixtures[:10]:
        print(f"- {f['home']} {f['score']} {f['away']} ({f['date']}) [leagueId={f['leagueId']}]")

    if not fixtures and all_matches:
        print("\nNo World Cup matches matched by team-name filter.")
        print("If this is during the tournament, inspect the leagueId values below")
        print("and add the correct one to WORLD_CUP_LEAGUE_IDS:")
        league_ids_seen = sorted(set(m['leagueId'] for m in all_matches if m['leagueId']))
        print(league_ids_seen[:30])

except Exception as e:
    print(f"Football data API unavailable ({e}). Falling back to RSS-only mode.")
    fixtures = []  # empty list - downstream prompts handle this gracefully

# --- 1c. Generate one idea per active category with LLM ---
# STRICT WORLD CUP 2026 MODE: ideas are generated ONLY from real World Cup
# 2026 fixture data pulled in section 1b. If no fixtures were found (e.g.
# tournament hasn't started, API issue, or RSS-fallback triggered), this
# cell stops here rather than falling back to generic football news -
# avoiding "off-topic" videos.

import anthropic

client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

if not fixtures:
    raise RuntimeError(
        "No World Cup 2026 fixtures available (section 1b returned empty). "
        "Strict World-Cup-only mode is enabled, so the pipeline stops here "
        "rather than generating an off-topic video from general football news. "
        "Re-run section 1b later, or check WORLD_CUP_LEAGUE_IDS / the national "
        "team filter if matches are happening but not being detected."
    )

print(f"{len(fixtures)} World Cup 2026 fixture(s) available for idea generation:")
for f in fixtures:
    print(f"- {f['home']} {f['score']} {f['away']} ({f['date']})")

# Hook styles - tag each idea with one of these so the growth report (section 8)
# can analyze which hook style performs best, in addition to category.
HOOK_STYLES = ["question", "stat_shock", "controversy", "prediction", "countdown"]

top_ideas = []
for cat in ACTIVE_CATEGORIES:
    angle = IDEA_CATEGORIES[cat]["angle"]

    ranking_prompt = f"""You are a social media strategist for a faceless World Cup 2026 Shorts channel.
Category: {cat}
Content angle for this category: {angle}

Below is REAL World Cup 2026 match data - this is the ONLY source of truth.
Pick ONE match from this list and build a topic around it that fits the
category and angle above. The topic MUST be about one of these specific
matches/teams - do not invent or reference any other match.

Give:
- 'title': a specific title naming the actual teams from the match you picked
- 'hook': a one-line angle/hook
- 'reason': why it's timely
- 'hook_style': pick the best fit from {HOOK_STYLES}
- 'home_team' and 'away_team': the exact team names from the match you picked (for b-roll search)

Respond ONLY as JSON: an object with keys 'category', 'title', 'hook', 'reason', 'hook_style', 'home_team', 'away_team'.

WORLD CUP 2026 MATCHES:
{json.dumps(fixtures, indent=2)}
"""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=500,
        messages=[{"role": "user", "content": ranking_prompt}]
    )

    raw_text = response.content[0].text.strip().replace('```json', '').replace('```', '').strip()
    idea = json.loads(raw_text)
    idea["category"] = cat  # ensure it's set even if the model omits it
    if idea.get("hook_style") not in HOOK_STYLES:
        idea["hook_style"] = "question"  # safe default if model returns something unexpected
    top_ideas.append(idea)

print(json.dumps(top_ideas, indent=2))

"""### 1.1 Deduplication — avoid reusing the same topic/fixture

Keeps a persistent log of topics already produced (saved to Google Drive so it survives across Colab sessions). Before generating ideas, we filter out anything matching a previously-used topic.

**How matching works**: a simple fingerprint based on team names + fixture date + category. This catches the obvious case (same match, same angle, run twice) without needing exact title matches.
"""

# Mount Drive so the history log persists across Colab sessions
from google.colab import drive
drive.mount('/content/drive')

HISTORY_PATH = "/content/drive/MyDrive/football_shorts_history.json"

import os, json, re

def load_history():
    if os.path.exists(HISTORY_PATH):
        with open(HISTORY_PATH) as f:
            return json.load(f)
    return []

def save_history(history):
    with open(HISTORY_PATH, 'w') as f:
        json.dump(history, f, indent=2)

def make_fingerprint(text, category=None):
    """Lowercase, strip punctuation, sort words -> rough content fingerprint.
    Two titles about the same fixture/topic usually share most key words
    even if phrased differently."""
    words = re.findall(r"[a-z0-9]+", text.lower())
    stop = {"the", "a", "an", "vs", "and", "for", "in", "of", "to", "world", "cup", "2026"}
    keywords = sorted(w for w in words if w not in stop and len(w) > 2)
    fp = "-".join(keywords)
    if category:
        fp = f"{category}:{fp}"
    return fp

def fingerprint_overlap(fp1, fp2, threshold=0.6):
    """Returns True if two fingerprints share enough keywords to be considered duplicates."""
    set1, set2 = set(fp1.split("-")), set(fp2.split("-"))
    if not set1 or not set2:
        return False
    overlap = len(set1 & set2) / min(len(set1), len(set2))
    return overlap >= threshold

history = load_history()
print(f"Loaded {len(history)} previously produced topics")

"""### 1.2 Posting Cadence Limiter

Checks how many videos were produced today (based on `produced_at` timestamps in history) and stops the run if you've hit your daily cap. Prevents accidental spam runs (e.g. re-running the notebook multiple times in a session) and keeps you within free YouTube API quota (~6 uploads/day max).
"""

from datetime import datetime, timezone

MAX_VIDEOS_PER_DAY = 3  # adjust to your posting schedule

today = datetime.now(timezone.utc).date()

# Count videos PRODUCED today (any attempt, including ones not yet uploaded)
produced_today = [
    h for h in history
    if datetime.fromisoformat(h['produced_at']).date() == today
]

# Count videos actually POSTED today (have a recorded youtube_video_id)
posted_today = [h for h in produced_today if h.get('youtube_video_id')]

print(f"Videos produced today: {len(produced_today)}")
print(f"Videos posted today: {len(posted_today)} / {MAX_VIDEOS_PER_DAY}")

if len(posted_today) >= MAX_VIDEOS_PER_DAY:
    raise RuntimeError(
        f"Daily cap of {MAX_VIDEOS_PER_DAY} POSTED videos already reached today. "
        "Stop here, or raise MAX_VIDEOS_PER_DAY if you're sure you want to continue."
    )

"""## 2. Script + Captions + Hashtags

Filters out any generated ideas that match recently produced topics, picks one, generates the script, then records it in the history log so it won't be reused.
"""

# --- Filter out duplicate ideas before selecting ---
fresh_ideas = []
for idea in top_ideas:
    fp = make_fingerprint(idea['title'], idea['category'])
    is_dup = any(fingerprint_overlap(fp, h['fingerprint']) for h in history)
    if is_dup:
        print(f"Skipping (duplicate of past topic): {idea['title']}")
    else:
        idea['_fingerprint'] = fp
        fresh_ideas.append(idea)

if not fresh_ideas:
    raise RuntimeError(
        "All generated ideas match recently produced topics. "
        "Try re-running step 1 (it re-randomizes categories) or widen ACTIVE_CATEGORIES."
    )

print(f"\n{len(fresh_ideas)} fresh idea(s) available")
for i, idea in enumerate(fresh_ideas):
    print(f"[{i}] ({idea['category']}) {idea['title']}")

# Choose which fresh idea to produce (0 = first)
SELECTED_IDEA_INDEX = 0
selected_idea = fresh_ideas[SELECTED_IDEA_INDEX]
selected_angle = IDEA_CATEGORIES[selected_idea["category"]]["angle"]
print("Selected category:", selected_idea['category'])
print("Selected idea:", selected_idea['title'])

script_prompt = f"""Write content for a faceless football YouTube Short based on this topic:

Category: {selected_idea['category']}
Content angle: {selected_angle}
Title: {selected_idea['title']}
Hook: {selected_idea['hook']}
Context: {selected_idea['reason']}

Requirements:
- Narration script: MUST be under 20 seconds when spoken (about 45-55 words MAXIMUM - this is a hard limit), punchy, hook in first 2 seconds, NO references to showing footage (the visuals will be generic stock football clips, not the actual match)- 4-6 short on-screen text overlay lines (3-6 words each) that sync roughly with the narration's key moments
- 8-10 relevant hashtags for YouTube Shorts (mix of broad football tags and specific ones)
- A YouTube title (under 100 characters) and description (2-3 sentences)

Respond ONLY as JSON with keys: 'narration', 'overlays' (list of strings), 'hashtags' (list of strings without #), 'yt_title', 'yt_description'.
"""

response = client.messages.create(
    model="claude-sonnet-4-6",
    max_tokens=1500,
    messages=[{"role": "user", "content": script_prompt}]
)

raw_text = response.content[0].text.strip().replace('```json', '').replace('```', '').strip()
script_data = json.loads(raw_text)

print("NARRATION:\n", script_data['narration'])
print("\nOVERLAYS:", script_data['overlays'])
print("\nHASHTAGS:", script_data['hashtags'])
print("\nYT TITLE:", script_data['yt_title'])

# Save
with open('/content/pipeline/output/script_data.json', 'w') as f:
    json.dump(script_data, f, indent=2)

# --- Record this topic in history so it isn't reused ---
from datetime import datetime, timezone

history.append({
    "fingerprint": selected_idea['_fingerprint'],
    "title": selected_idea['title'],
    "category": selected_idea['category'],
    "hook_style": selected_idea.get('hook_style', ''),
    "home_team": selected_idea.get('home_team', ''),
    "away_team": selected_idea.get('away_team', ''),
    "yt_title": script_data['yt_title'],
    "produced_at": datetime.now(timezone.utc).isoformat(),
    "broll_ids": [],  # filled in after step 4 runs; see note below
})
save_history(history)
print(f"History updated. Total topics logged: {len(history)}")
print("Note: after running step 4 (b-roll download), re-run the next cell to record broll_ids too.")

"""## 3. Voiceover (Edge-TTS, free)"""

import edge_tts
import asyncio

# Voice options: en-US-GuyNeural, en-US-AriaNeural, en-GB-RyanNeural, en-AU-WilliamNeural, etc.
VOICE = "en-US-GuyNeural"

AUDIO_PATH = "/content/pipeline/assets/voiceover.mp3"

async def generate_voiceover(text, out_path, voice=VOICE):
    communicate = edge_tts.Communicate(text, voice)
    await communicate.save(out_path)

await generate_voiceover(script_data['narration'], AUDIO_PATH)
print("Voiceover saved:", AUDIO_PATH)

# Check duration
import subprocess
result = subprocess.run(
    ['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', AUDIO_PATH],
    capture_output=True, text=True
)
duration = float(result.stdout.strip())
print(f"Audio duration: {duration:.1f}s")
MAX_DURATION_SECONDS = 20.0
if duration > MAX_DURATION_SECONDS:
    raise ValueError(
        f"Voiceover is {duration:.1f}s, which exceeds the {MAX_DURATION_SECONDS}s "
        f"Shorts cap. Re-run section 2 (script generation) to get a shorter "
        f"narration, or manually shorten script_data['narration'] and re-run "
        f"this cell."
    )

"""## 4. B-roll — Free stock football footage from Pexels

Searches Pexels for relevant football clips, downloads a few, and we'll concatenate/trim them to match the audio length.

**Variety check**: tracks which Pexels video IDs have been used recently (via the same history log) and skips them, so consecutive videos don't reuse identical b-roll.
"""

import subprocess

def search_pexels_videos(query, per_page=5):
    url = "https://api.pexels.com/videos/search"
    headers = {"Authorization": PEXELS_API_KEY}
    params = {"query": query, "per_page": per_page, "orientation": "portrait"}
    resp = requests.get(url, headers=headers, params=params)
    resp.raise_for_status()
    return resp.json().get('videos', [])

def get_best_video_file(video, target_width=1080):
    """Pick the highest-quality vertical (or closest) file under a size cap."""
    files = video.get('video_files', [])
    candidates = sorted(files, key=lambda f: abs(f.get('width', 0) - target_width))
    return candidates[0] if candidates else None

# Recently used Pexels video IDs (last 20 videos produced)
recent_broll_ids = set()
for h in history[-20:]:
    recent_broll_ids.update(h.get('broll_ids', []))

# Search terms - generic football b-roll, NOT tied to any specific broadcast.
# Pulls in the actual team names from the chosen idea (if available) so
# clips are at least thematically closer to the topic - e.g. "Brazil
# football team" or "Morocco national team" instead of fully generic terms.
# Note: Pexels has limited stock footage of specific national teams, so this
# may still fall back to generic results for less-covered teams - that's
# expected, not an error.
home_team = selected_idea.get('home_team', '')
away_team = selected_idea.get('away_team', '')

SEARCH_TERMS = ["football stadium crowd", "soccer player celebration", "football match action"]
if home_team:
    SEARCH_TERMS.insert(0, f"{home_team} football team")
if away_team:
    SEARCH_TERMS.insert(1, f"{away_team} football team")

# Cap total terms so we don't download more clips than needed for a <20s Short
SEARCH_TERMS = SEARCH_TERMS[:4]

print("B-roll search terms:", SEARCH_TERMS)

downloaded_clips = []
used_broll_ids = []
for term in SEARCH_TERMS:
    videos = search_pexels_videos(term, per_page=5)
    # Prefer videos not used recently
    candidates = [v for v in videos if v['id'] not in recent_broll_ids] or videos
    for v in candidates[:1]:
        file_info = get_best_video_file(v)
        if not file_info:
            continue
        out_path = f"/content/pipeline/assets/broll_{len(downloaded_clips)}.mp4"
        r = requests.get(file_info['link'], stream=True)
        with open(out_path, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
        downloaded_clips.append(out_path)
        used_broll_ids.append(v['id'])
        print("Downloaded:", out_path, "from term:", term, "(video id:", v['id'], ")")

print(f"\nTotal clips downloaded: {len(downloaded_clips)}")

# --- Trim each clip to a few seconds ---
CLIP_TRIM_SECONDS = 8

trimmed_clips = []
for i, clip in enumerate(downloaded_clips):
    trimmed_path = f"/content/pipeline/assets/broll_trimmed_{i}.mp4"
    subprocess.run(
        ['ffmpeg', '-y', '-i', clip, '-t', str(CLIP_TRIM_SECONDS), '-c', 'copy', trimmed_path],
        capture_output=True
    )
    trimmed_clips.append(trimmed_path)

downloaded_clips = trimmed_clips
print(f"Trimmed {len(downloaded_clips)} clips to {CLIP_TRIM_SECONDS}s each")

# --- Run this AFTER step 4 (b-roll download) to record which clips were used ---
history[-1]["broll_ids"] = used_broll_ids
save_history(history)
print("Recorded b-roll IDs for this video:", used_broll_ids)

"""## 5. Video Assembly with FFmpeg

- Concatenate b-roll clips, trim/loop to match voiceover duration
- Resize/crop to 1080x1920 (9:16)
- Mux with voiceover audio
"""

import subprocess

RAW_VIDEO = "/content/pipeline/assets/broll_combined.mp4"
FINAL_VIDEO_NO_CAPTIONS = "/content/pipeline/assets/video_no_captions.mp4"

# 1. Build concat list
concat_list_path = "/content/pipeline/assets/concat_list.txt"
with open(concat_list_path, 'w') as f:
    for clip in downloaded_clips:
        f.write(f"file '{clip}'\n")

# 2. Concatenate (re-encode to ensure consistent format)
subprocess.run([
    'ffmpeg', '-y', '-f', 'concat', '-safe', '0', '-i', concat_list_path,
    '-vf', 'scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920',
    '-c:v', 'libx264', '-preset', 'fast', '-an',
    RAW_VIDEO
], check=True)

# 3. Loop/trim raw video to match audio duration, then mux with audio
subprocess.run([
    'ffmpeg', '-y',
    '-stream_loop', '-1', '-i', RAW_VIDEO,
    '-i', AUDIO_PATH,
    '-c:v', 'libx264', '-preset', 'fast',
    '-c:a', 'aac',
    '-t', str(duration),
    '-map', '0:v:0', '-map', '1:a:0',
    '-shortest',
    FINAL_VIDEO_NO_CAPTIONS
], check=True)

print("Base video assembled:", FINAL_VIDEO_NO_CAPTIONS)

"""## 5.1 Thumbnail Generator

YouTube Shorts auto-picks a frame as the thumbnail, but a custom "stat card" thumbnail
(big number/score + short label) tends to perform better in feeds and search.

This generates a simple branded thumbnail using Pillow: a dark background, a large headline
stat or score pulled from the script's overlays, and the category as a small label.
Output is a 1080x1920 JPEG (matches Shorts aspect ratio; YouTube also accepts this for
the custom thumbnail set via `videos.thumbnails.set`, though it will be cropped for
display in some surfaces).
"""

from PIL import Image, ImageDraw, ImageFont

THUMBNAIL_PATH = "/content/pipeline/output/thumbnail.jpg"

def make_thumbnail(headline_text, subtext, category_label, out_path,
                    width=1080, height=1920, bg_color=(15, 20, 35)):
    img = Image.new("RGB", (width, height), color=bg_color)
    draw = ImageDraw.Draw(img)

    # Try a bold system font, fall back to default if unavailable
    try:
        headline_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 110)
        sub_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 60)
        label_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 40)
    except OSError:
        headline_font = ImageFont.load_default()
        sub_font = ImageFont.load_default()
        label_font = ImageFont.load_default()

    # Accent bar
    draw.rectangle([(0, 0), (width, 18)], fill=(0, 200, 120))

    # Category label, top-left
    draw.text((50, 60), category_label.upper().replace("_", " "), font=label_font, fill=(0, 200, 120))

    # Headline text, centered, word-wrapped
    def wrap_text(text, font, max_width):
        words = text.split()
        lines, current = [], ""
        for w in words:
            test = (current + " " + w).strip()
            bbox = draw.textbbox((0, 0), test, font=font)
            if bbox[2] - bbox[0] <= max_width:
                current = test
            else:
                lines.append(current)
                current = w
        if current:
            lines.append(current)
        return lines

    lines = wrap_text(headline_text, headline_font, width - 100)
    line_height = 130
    total_height = len(lines) * line_height
    start_y = (height - total_height) // 2

    for i, line in enumerate(lines):
        bbox = draw.textbbox((0, 0), line, font=headline_font)
        text_w = bbox[2] - bbox[0]
        x = (width - text_w) // 2
        y = start_y + i * line_height
        draw.text((x, y), line, font=headline_font, fill=(255, 255, 255))

    # Subtext near bottom
    if subtext:
        bbox = draw.textbbox((0, 0), subtext, font=sub_font)
        text_w = bbox[2] - bbox[0]
        x = (width - text_w) // 2
        draw.text((x, height - 220), subtext, font=sub_font, fill=(200, 200, 200))

    img.save(out_path, quality=90)
    return out_path

# Use the first overlay line as the headline, and the YT title (shortened) as subtext
headline = script_data['overlays'][0] if script_data.get('overlays') else script_data['yt_title']
subtext = selected_idea['title'][:40]

make_thumbnail(headline, subtext, selected_idea['category'], THUMBNAIL_PATH)
print("Thumbnail saved:", THUMBNAIL_PATH)

from IPython.display import Image as IPImage
IPImage(THUMBNAIL_PATH, width=200)

"""## 6. Word-level captions with Whisper

Transcribes the voiceover with word-level timestamps so captions can appear synced, then burns them into the video using FFmpeg's `drawtext` (via an SRT/ASS subtitle file for cleaner styling).
"""

import whisper

model = whisper.load_model("base")  # 'tiny' is faster, 'small'/'base' more accurate
result = model.transcribe(AUDIO_PATH, word_timestamps=True)

# Flatten word-level segments
words = []
for segment in result['segments']:
    for w in segment.get('words', []):
        words.append({"word": w['word'].strip(), "start": w['start'], "end": w['end']})

print(f"Transcribed {len(words)} words")
print(words[:10])

# Build an ASS subtitle file with bold, centered, animated-feel captions
# Groups words into short chunks (2-4 words) for punchy Shorts-style captions

ASS_PATH = "/content/pipeline/assets/captions.ass"

def format_ass_time(seconds):
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    return f"{h}:{m:02d}:{s:05.2f}"

# Group words into chunks of ~3
CHUNK_SIZE = 3
chunks = []
for i in range(0, len(words), CHUNK_SIZE):
    chunk_words = words[i:i+CHUNK_SIZE]
    if not chunk_words:
        continue
    text = " ".join(w['word'] for w in chunk_words)
    chunks.append({
        "start": chunk_words[0]['start'],
        "end": chunk_words[-1]['end'],
        "text": text
    })

ass_header = """[Script Info]
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Caption,Montserrat,90,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,4,2,2,60,60,500,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

events = []
for c in chunks:
    start = format_ass_time(c['start'])
    end = format_ass_time(c['end'])
    text = c['text'].upper()
    events.append(f"Dialogue: 0,{start},{end},Caption,,0,0,0,,{text}")

with open(ASS_PATH, 'w') as f:
    f.write(ass_header)
    f.write("\n".join(events))

print("Subtitle file written:", ASS_PATH)
print(f"{len(chunks)} caption chunks")

# Burn captions into video
FINAL_VIDEO = "/content/pipeline/output/final_short.mp4"

subprocess.run([
    'ffmpeg', '-y',
    '-i', FINAL_VIDEO_NO_CAPTIONS,
    '-vf', f"ass={ASS_PATH}",
    '-c:v', 'libx264', '-preset', 'fast',
    '-c:a', 'copy',
    FINAL_VIDEO
], check=True)

print("Final video with captions:", FINAL_VIDEO)

# Preview in Colab
from IPython.display import Video
Video(FINAL_VIDEO, embed=True, width=360)

"""## 6.1 Review Dashboard (Google Sheets)

Instead of digging through Drive folders, each finished video gets a row in a Google Sheet:
title, category, hook style, hashtags, a Drive link to preview the video, and a **Status** column
(`pending` / `approved` / `rejected`).

Workflow:
1. This cell saves the video to Drive and adds a row with status `pending`.
2. Open the Sheet on your phone or desktop, tap the Drive link to preview the video.
3. Change the Status cell to `approved` (or `rejected`).
4. Run section 7 - it only uploads videos marked `approved` that haven't been uploaded yet.

**One-time setup**: create a Google Sheet, share it, and note its Sheet ID (the long string in its URL). Paste it below.
"""

!pip install -q gspread google-auth

import gspread
from google.colab import auth as colab_auth

# Authenticate with your Google account (covers Sheets + Drive access)
colab_auth.authenticate_user()

import google.auth
creds, _ = google.auth.default()
gc = gspread.authorize(creds)

# --- Fill this in: open your Sheet's URL, copy the ID between /d/ and /edit ---
REVIEW_SHEET_ID = "1rpPNGWNcNkWQzCjP4U-1id6L7p-ce6B_j0W7M17uBlI"

sheet = gc.open_by_key(REVIEW_SHEET_ID).sheet1

# Ensure header row exists
EXPECTED_HEADERS = [
    "row_id", "produced_at", "category", "hook_style", "yt_title",
    "hashtags", "drive_link", "thumbnail_link", "status", "youtube_video_id"
]
existing_headers = sheet.row_values(1)
if existing_headers != EXPECTED_HEADERS:
    sheet.update('A1', [EXPECTED_HEADERS])
    print("Header row created/updated")
else:
    print("Header row OK")

# --- Save video to Drive + add a pending row to the review sheet ---
import shutil
from datetime import datetime

REVIEW_QUEUE_DIR = "/content/drive/MyDrive/football_shorts_review_queue"
os.makedirs(REVIEW_QUEUE_DIR, exist_ok=True)

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
safe_title = "".join(c if c.isalnum() or c in " -_" else "" for c in script_data['yt_title'])[:50].strip()
row_id = f"{timestamp}_{safe_title}"
queue_subdir = os.path.join(REVIEW_QUEUE_DIR, row_id)
os.makedirs(queue_subdir, exist_ok=True)

# Copy video + thumbnail (thumbnail created in section 5.1, may not exist if skipped)
video_dest = os.path.join(queue_subdir, "video.mp4")
shutil.copy(FINAL_VIDEO, video_dest)

thumb_dest = None
if 'THUMBNAIL_PATH' in globals() and os.path.exists(THUMBNAIL_PATH):
    thumb_dest = os.path.join(queue_subdir, "thumbnail.jpg")
    shutil.copy(THUMBNAIL_PATH, thumb_dest)

with open(os.path.join(queue_subdir, "metadata.json"), 'w') as f:
    json.dump({
        "yt_title": script_data['yt_title'],
        "yt_description": script_data['yt_description'],
        "hashtags": script_data['hashtags'],
        "category": selected_idea['category'],
        "hook_style": selected_idea.get('hook_style', ''),
        "narration": script_data['narration'],
    }, f, indent=2)

# Drive 'preview' links use the folder path - simplest is to note the path,
# since Colab's Drive mount maps directly to 'My Drive' in the Drive app/web UI.
drive_relative_path = f"football_shorts_review_queue/{row_id}/video.mp4"
thumb_relative_path = f"football_shorts_review_queue/{row_id}/thumbnail.jpg" if thumb_dest else ""

# Append row to the review sheet.
# If AUTO_APPROVE is True, mark as 'approved' immediately so section 7
# uploads it without needing manual edits to the sheet.
initial_status = "approved" if AUTO_APPROVE else "pending"

sheet.append_row([
    row_id,
    datetime.now().isoformat(),
    selected_idea['category'],
    selected_idea.get('hook_style', ''),
    script_data['yt_title'],
    ", ".join(script_data['hashtags']),
    drive_relative_path,
    thumb_relative_path,
    initial_status,
    ""
])

print(f"Saved to review queue: {queue_subdir}")
print(f"Added row '{row_id}' to review sheet with status={initial_status}")
if AUTO_APPROVE:
    print("AUTO_APPROVE is on - this video will be uploaded when section 7 runs, no manual step needed.")
else:
    print("\nOpen the sheet, find this row, open the video via Drive (path above), ")
    print("then change the Status column to 'approved' or 'rejected'.")

"""## 7. Upload Approved Videos to YouTube Shorts

Requires OAuth credentials - see the separate setup guide for getting `client_secrets.json` from Google Cloud Console.

First run will open a browser auth flow; subsequent runs reuse the saved token (`token.json`).

**This step only uploads videos marked `approved` in the Google Sheet** (section 6.1) that haven't been uploaded yet. Review and approve rows in the sheet first, then run this section - it will batch-process everything approved.
"""

!pip install -q google-api-python-client google-auth-oauthlib google-auth-httplib2

import os
import google.auth.transport.requests
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# youtube.upload: lets us create videos
# youtube.force-ssl: lets us set custom thumbnails and post comments
# youtube.readonly + yt-analytics.readonly: needed for section 8 (performance monitor)
SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube.force-ssl",
    "https://www.googleapis.com/auth/youtube.readonly",
    "https://www.googleapis.com/auth/yt-analytics.readonly",
]
CLIENT_SECRETS_FILE = "/content/drive/MyDrive/Colab Notebooks/client_secrets.json"
TOKEN_FILE = "/content/token.json"

def run_manual_console_flow(client_secrets_file, scopes):
    flow = Flow.from_client_secrets_file(
        client_secrets_file,
        scopes=scopes,
        redirect_uri="urn:ietf:wg:oauth:2.0:oob"
    )
    auth_url, _ = flow.authorization_url(prompt='consent')
    print("1. Open this URL in your browser:")
    print(auth_url)
    print("\n2. Sign in, grant permission, and copy the code shown.")
    code = input("3. Paste the authorization code here: ").strip()
    flow.fetch_token(code=code)
    return flow.credentials

def get_youtube_service():
    creds = None
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(google.auth.transport.requests.Request())
        else:
            creds = run_manual_console_flow(CLIENT_SECRETS_FILE, SCOPES)
        with open(TOKEN_FILE, 'w') as f:
            f.write(creds.to_json())
    return build("youtube", "v3", credentials=creds)

youtube = get_youtube_service()
print("YouTube service authenticated")

def upload_short(youtube, video_path, title, description, tags, privacy_status="private"):
    """privacy_status: 'private', 'unlisted', or 'public'.
    Start with 'private' or 'unlisted' to review before going live."""
    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": "17"  # Sports
        },
        "status": {
            "privacyStatus": privacy_status,
            "selfDeclaredMadeForKids": False
        }
    }

    media = MediaFileUpload(video_path, chunksize=-1, resumable=True, mimetype="video/mp4")

    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"Upload progress: {int(status.progress() * 100)}%")

    print("Upload complete. Video ID:", response['id'])
    return response


def set_thumbnail(youtube, video_id, thumbnail_path):
    """Set a custom thumbnail. Requires the youtube.force-ssl scope and
    that the channel has thumbnail-setting enabled (verified channels can
    always do this; new/unverified channels may need phone verification
    in YouTube Studio first - see setup guide)."""
    try:
        youtube.thumbnails().set(
            videoId=video_id,
            media_body=MediaFileUpload(thumbnail_path, mimetype="image/jpeg")
        ).execute()
        print("Custom thumbnail set")
    except Exception as e:
        print(f"Could not set thumbnail (channel may need phone verification): {e}")


def post_pinned_comment(youtube, video_id, comment_text):
    """Post a comment and pin it. Pinning isn't directly exposed by the API,
    so this posts the comment - pin it manually in YouTube Studio, or rely on
    it being the first comment which YouTube often surfaces prominently."""
    try:
        result = youtube.commentThreads().insert(
            part="snippet",
            body={
                "snippet": {
                    "videoId": video_id,
                    "topLevelComment": {
                        "snippet": {"textOriginal": comment_text}
                    }
                }
            }
        ).execute()
        print("Posted comment:", comment_text)
        print("Note: pin it manually in YouTube Studio for max visibility (Studio > Comments > pin icon).")
        return result
    except Exception as e:
        print(f"Could not post comment: {e}")
        return None

# --- Process approved rows from the review sheet ---
# A row is processed if status == 'approved' and youtube_video_id is empty.

all_rows = sheet.get_all_records()

approved_to_upload = []
for idx, row in enumerate(all_rows, start=2):  # row 1 is the header
    if row['status'].strip().lower() == 'approved' and not row['youtube_video_id']:
        approved_to_upload.append((idx, row))

print(f"{len(approved_to_upload)} approved video(s) ready to upload")

for sheet_row_num, row in approved_to_upload:
    row_id = row['row_id']
    queue_dir = f"/content/drive/MyDrive/football_shorts_review_queue/{row_id}"
    video_path = os.path.join(queue_dir, "video.mp4")
    thumb_path = os.path.join(queue_dir, "thumbnail.jpg")
    meta_path = os.path.join(queue_dir, "metadata.json")

    if not os.path.exists(video_path):
        print(f"Skipping {row_id}: video file not found at {video_path}")
        continue

    with open(meta_path) as f:
        meta = json.load(f)

    full_description = meta['yt_description'] + "\n\n" + " ".join(f"#{tag}" for tag in meta['hashtags'])

    print(f"\nUploading: {meta['yt_title']}")
    upload_response = upload_short(
        youtube,
        video_path,
        title=meta['yt_title'],
        description=full_description,
        tags=meta['hashtags'],
        privacy_status="private"  # flip to 'public' once you're confident, or change manually in Studio
    )
    video_id = upload_response['id']

    # Custom thumbnail, if generated
    if os.path.exists(thumb_path):
        set_thumbnail(youtube, video_id, thumb_path)

    # Pinned/first comment with a discussion prompt - boosts engagement
    comment_text = f"What did you think? Drop your prediction for the next match below \U0001F447 #{meta['hashtags'][0] if meta['hashtags'] else 'football'}"
    post_pinned_comment(youtube, video_id, comment_text)

    # Update the sheet row with the video ID
    sheet.update_cell(sheet_row_num, EXPECTED_HEADERS.index('youtube_video_id') + 1, video_id)

    # Update history if this row corresponds to the most recent entry
    for h in history:
        if h.get('yt_title') == meta['yt_title'] and not h.get('youtube_video_id'):
            h['youtube_video_id'] = video_id
            break
    save_history(history)

    print(f"Done: video ID {video_id} recorded in sheet and history")

"""## 8. Channel Performance Monitor & Growth Recommendations

Pulls performance stats for your recent uploads via the YouTube Analytics API, summarizes what's working, and asks the LLM for concrete suggestions on improving views/followers — then feeds the best-performing categories back into future idea ranking.

Run this periodically (e.g. weekly), not every single video cycle.
"""

# Reuses the same token created in section 7's auth cell (now includes
# analytics scopes - see SCOPES in that cell). If you get an
# "insufficient authentication scopes" error here, delete TOKEN_FILE and
# re-run section 7's auth cell to re-authenticate with all scopes at once.

from googleapiclient.discovery import build as build_service

def get_analytics_service():
    creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    if creds.expired and creds.refresh_token:
        creds.refresh(google.auth.transport.requests.Request())
    return build_service("youtubeAnalytics", "v2", credentials=creds)

analytics = get_analytics_service()
print("YouTube Analytics service ready")

# --- Ask the LLM for growth recommendations based on this data ---
perf_summary = json.dumps(performance, indent=2)

growth_prompt = f"""You are a YouTube Shorts growth strategist for a faceless football channel.
Below is performance data for recent videos (views, average view percentage,
subscribers gained, likes, shares), with each video tagged by content category
AND hook style (question, stat_shock, controversy, prediction, countdown).

Analyze this data and provide:
1. Which categories AND which hook styles are over/under-performing, and why that might be
2. 3-5 concrete, actionable changes to improve views/followers (hooks, posting times,
   caption style, hashtag strategy, video length, thumbnail/title patterns, etc.)
3. A recommended category + hook style mix for the next batch of videos (which
   combinations to prioritize, which to reduce)

Respond in plain text, organized under those three headings. Be specific and concise.

DATA:
{perf_summary}
"""

response = client.messages.create(
    model="claude-sonnet-4-6",
    max_tokens=1200,
    messages=[{"role": "user", "content": growth_prompt}]
)

growth_report = response.content[0].text
print(growth_report)

# Save report with timestamp for tracking over time
report_path = f"/content/drive/MyDrive/football_shorts_growth_report_{date.today().isoformat()}.txt"
with open(report_path, 'w') as f:
    f.write(growth_report)
print(f"\nSaved report to: {report_path}")

# --- Optional: bias future idea selection toward best-performing categories ---
# Computes average views per category and lets you weight ACTIVE_CATEGORIES
# selection (in section 1.0) toward winners.

from collections import defaultdict

category_views = defaultdict(list)
for p in performance:
    category_views[p['category']].append(p['views'])

category_avg = {cat: sum(v)/len(v) for cat, v in category_views.items() if v}
print("Average views by category:")
for cat, avg in sorted(category_avg.items(), key=lambda x: x[1], reverse=True):
    print(f"  {cat}: {avg:.0f}")

# Save weights so section 1.0 can optionally load and use them next session
weights_path = "/content/drive/MyDrive/football_shorts_category_weights.json"
with open(weights_path, 'w') as f:
    json.dump(category_avg, f, indent=2)

print(f"\nSaved category weights to: {weights_path}")
print("Tip: in section 1.0, load this file and use weighted random.choices() ")
print("instead of random.sample() to favor higher-performing categories.")

"""## Notes & next steps

- **Scheduling**: Colab doesn't run on a fixed schedule. To automate fully, either (a) run this manually a few times a week, or (b) move this script to a free always-on host (e.g. a scheduled GitHub Action, Render cron job, or a Raspberry Pi) once you've validated the pipeline here.
- **Quality**: videos are uploaded as `private` by default. Switch to `public` in YouTube Studio once you've watched the upload, or change `privacy_status` in section 7 if you trust the pipeline fully.
- **Pexels rate limits**: free tier is 200 requests/hour - fine for a few videos a day.
- **API-Football free tier**: 100 requests/day - section 1b now falls back to RSS-only mode if this fails.
- **Variety**: rotate search terms in step 4 and vary `SELECTED_IDEA_INDEX` in step 2 to avoid repetitive visuals across videos.
- **Daily cap**: section 1.2 limits how many videos are produced per day (default 3). Adjust `MAX_VIDEOS_PER_DAY` to match your schedule and YouTube API quota (~6 uploads/day max on free tier).
- **Review dashboard**: section 6.1 writes a row per video to a Google Sheet with a Drive link, thumbnail, hashtags, and a Status column. Mark rows `approved` from your phone, then run section 7 to batch-upload everything approved.
- **Thumbnails**: section 5.1 generates a simple stat-card thumbnail automatically; section 7 sets it as the video's custom thumbnail (requires phone-verified channel - see setup guide).
- **Pinned comment**: section 7 posts an engagement-prompt comment on each upload; pin it manually in Studio for best visibility.
- **Growth loop**: run section 8 weekly. It pulls views/likes/subscriber data per video (now including hook style), asks the LLM for concrete improvement suggestions, and saves category performance weights you can use to bias future idea selection in section 1.0.
"""